//  Turn off the green light (P2)
basic.forever(function on_forever() {
    //  Define a function called on_forever
    pins.digitalWritePin(DigitalPin.P0, 1)
    basic.showString("Stop!")
    //  Turn on the red light (P0)
    basic.pause(5000)
    //  Pause for 5 seconds
    basic.pause(5000)
    //  Pause for an additional 5 seconds
    pins.digitalWritePin(DigitalPin.P0, 0)
    //  Turn off the red light (P0)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.showString("Get Ready!")
    //  Turn on the amber light (P1)
    basic.pause(5000)
    basic.pause(5000)
    pins.digitalWritePin(DigitalPin.P1, 0)
    //  Turn off the amber light (P1)
    pins.digitalWritePin(DigitalPin.P2, 1)
    basic.showString("Move!")
    //  Turn on the green light (P2)
    basic.pause(5000)
    basic.pause(5000)
    pins.digitalWritePin(DigitalPin.P2, 0)
})
